let Data = [
  {
    id: "1",
    name: "Bodhi Dharma",
    email: "BodhiDharma@xyz.com",
    company: "SportZ",
    role: "Head",
    recent: "5 minutes back",
  },
  {
    id: "2",
    name: "Galleleo",

    email: "galleleo@space.com",
    company: "Space spot",
    role: "Founder",
    recent: "12 minutes back",
  },
  {
    id: "3",
    name: "Picasso",
    email: "picasso@art.com",
    company: "D-Art",
    role: "member",
    recent: "22 minutes back",
  },
  {
    id: "4",
    name: "Narendra",
    email: "yog@yog.com",
    company: "Well",
    role: "Ceo",
    recent: "15 minutes back",
  },
  {
    id: "5",
    name: "Mistry",
    email: "Mistry@mason.com",
    company: "Miss-Tree",
    role: "Worker",
    recent: "1 hour back",
  },
  {
    id: "6",
    name: "Khaara",
    email: "Khaara@gmail.com",
    company: "Saline Co",
    role: "Manager",
    recent: "45 minutes back",
  },
  {
    id: "7",
    name: "Shreyansh",
    email: "shreyansh@raincode.com",
    company: "RainCode",
    role: "Developer",
    recent: "5 minutes back",
  },
  {
    id: "8",
    name: "Wonder Woman",
    email: "wonder@woman.com",
    company: "Wonder Security",
    role: "HR",
    recent: "23 minutes back",
  },
  {
    id: "9",
    name: "Baba Ramdev",
    email: "anulom@vilom.com",
    company: "Kapaal Bhati",
    role: "Instructer",
    recent: "10 minutes back",
  },
  {
    id: "10",
    name: "Jhon wick",
    email: "jhon@gmail.com",
    company: "Social",
    role: "Freelancer",
    recent: "50 minutes back",
  },
  {
    id: "11",
    name: "Indra",
    email: "indra@swarg.com",
    company: "Indra Hotels ",
    role: "Manager",
    recent: "12 minutes back",
  },
  {
    id: "12",
    name: "Salmon",
    email: "salmon@gmail.com",
    company: "Fisher-E",
    role: "Fisher man",
    recent: "33 minutes back",
  },
];

module.exports = Data;
