let Profiles = [
  {
    id: "1",
    title: "call betty",
    type: "call",
    associated: "betty",
    status: "completed",
    date: "15/07/2020",
  },
  {
    id: "2",
    title: "info about evening event ",

    type: "Video Call",
    associated: "Bahubali",
    status: "active",
    date: "15/07/2020",
  },
  {
    id: "3",
    title: "car servicing",
    type: "call",
    associated: "bablu repairing",
    status: "active",
    date: "16/072020",
  },
  {
    id: "4",
    title: "send product finalizing email",
    type: "email",
    associated: "developer team",
    status: "completed",
    date: "16/072020",
  },
  {
    id: "5",
    title: "send new pitch to financers",
    type: "email",
    associated: "financers",
    status: "active",
    date: "16/072020",
  },
  {
    id: "6",
    title: "long drive",
    type: "random",
    associated: "friends",
    status: "active",
    date: "18/072020",
  },
  {
    id: "7",
    title: "meeting for marketing",
    type: "meeting",
    associated: "marketing head",
    status: "active",
    date: "16/072020",
  },
  {
    id: "7",
    title: "pickup pablo for dinner",
    type: "random",
    associated: "pablo",
    status: "active",
    date: "16/072020",
  },
  {
    id: "8",
    title: "get new hair cut",
    type: "random",
    associated: "me",
    status: "active",
    date: "16/072020",
  },
  {
    id: "9",
    title: "meeting with developers about ongoing project",
    type: "meeting",
    associated: "dev team",
    status: "completed",
    date: "17/072020",
  },
  {
    id: "10",
    title: "call aayush",
    type: "call",
    associated: "aayush",
    status: "active",
    date: "16/072020",
  },
  {
    id: "11",
    title: "buy groceries",
    type: "shoppping",
    associated: "me",
    status: "completed",
    date: "20/072020",
  },
];
module.exports = Profiles;
